import turtle

turtle.penup()
turtle.right(90)
turtle.pensize(50)
turtle.forward(310)
turtle.right(180)
turtle.pendown()
turtle.color("brown")
turtle.forward(200)

turtle.begin_fill()
turtle.color("green")
turtle.pensize(40)
turtle.left(90)
turtle.forward(250)
turtle.right(120)
turtle.forward(500)
turtle.right(120)
turtle.forward(500)
turtle.right(120)
turtle.forward(250)
turtle.end_fill()

turtle.right(90)
turtle.penup()
turtle.forward(420)
turtle.pendown()
turtle.color("yellow")
turtle.dot(50)
turtle.penup()
turtle.right(180)
turtle.forward(100)
turtle.pendown()
turtle.color("red")
turtle.dot(50)

turtle.penup()
turtle.right(0)
turtle.forward(100)
turtle.pendown()
turtle.color("gold")
turtle.dot(50)

turtle.penup()
turtle.right(0)
turtle.forward(100)
turtle.pendown()
turtle.color("yellow")
turtle.dot(50)


turtle.penup()
turtle.right(90)
turtle.forward(100)
turtle.pendown()
turtle.color("red")
turtle.dot(50)


turtle.penup()
turtle.right(180)
turtle.forward(200)
turtle.pendown()
turtle.color("pink")
turtle.dot(50)

turtle.bgcolor("sky blue")

turtle.done()
# turtle.mainloop()