import turtle

# This turtle is CAT
cat = turtle.Turtle()
cat.screen.bgcolor('powder blue')
cat.speed(0.)
cat.showturtle()
cat.width(10)
cat.color('medium orchid', 'blue violet')
cat.begin_fill()
cat.forward(90)
cat.left(90)
cat.forward(100)
cat.right(90)
cat.left(90)
cat .left(90)
cat.forward(90)
cat.left(90)
cat.forward(100)
cat.end_fill()
cat.hideturtle()

# This turtle is ted
ted=turtle.Turtle()
ted.speed(0.)
ted.showturtle()
ted.width(10)
ted.penup()
ted.goto(-200,0)
ted.color('dark orange','orange red')
ted.begin_fill()
ted.pendown()
ted.circle(60)
ted.end_fill()
ted.hideturtle()

# this is a fred
fred=turtle.Turtle()
fred.showturtle()
fred.speed(10.)
fred.penup()
fred.goto(0,-30)
fred.left(90)
fred.left(90)
fred.forward(100)
fred.left(90)
fred.forward(89)
fred.write("To:mami", font=('Arial', 27, "normal"))
fred.left(90)
fred.forward(200)
fred.write("I bet you can't do that", font=("Arial", 24, "normal"))

# start.
t = turtle.Turtle()
t.speed(0.)
t.color('dark blue', 'medium spring green')
t.penup()
t.goto(150, 200)
t.begin_fill()
t.pendown()
for x in range(1,  20):
  t.forward(100)
  t.left(95)
t.end_fill()

fred.hideturtle()
turtle.done()
